# Borland C++ >=5.5

!ifdef debug
OPT= debug=1
!else
OPT= 
!endif

all:
	cd cv\make
	make -f makefile.bcc $(OPT)
	cd ..\..
	cd cvaux\make
	make -f makefile.bcc $(OPT)
	cd ..\..
	cd otherlibs\highgui
	make -f makefile.bcc $(OPT)
	cd ..\..
	cd tests\trs\make
	make -f makefile.bcc $(OPT)
	cd ..\..\..
	cd tests\cv\src
	make -f makefile.bcc $(OPT)
	cd ..\..\..
	cd samples\c
	make -f makefile.bcc $(OPT)
	cd ..\..