# Makefile for Borland C++ >=5.5

CXX = bcc32
LINK = bcc32

!ifdef debug

SUFFIX = d
DR = _Dbg

!else

SUFFIX = 
DR = _Rls

!endif

OUTBIN = ..\..\..\bin\cvtest$(SUFFIX).exe
OUTLIB = ..\..\..\lib\cvtest$(SUFFIX).lib

OBJS = ..\..\..\_temp\cvtest$(DR)_bcc\aabsdiff.obj \
..\..\..\_temp\cvtest$(DR)_bcc\aaccum.obj \
..\..\..\_temp\cvtest$(DR)_bcc\aadaptthresh.obj \
..\..\..\_temp\cvtest$(DR)_bcc\aapproxpoly.obj \
..\..\..\_temp\cvtest$(DR)_bcc\aarithm.obj \
..\..\..\_temp\cvtest$(DR)_bcc\aarrayiterator.obj \
..\..\..\_temp\cvtest$(DR)_bcc\abackproject.obj \
..\..\..\_temp\cvtest$(DR)_bcc\acalccontrasthist.obj \
..\..\..\_temp\cvtest$(DR)_bcc\acalculate.obj \
..\..\..\_temp\cvtest$(DR)_bcc\acameracalibration.obj \
..\..\..\_temp\cvtest$(DR)_bcc\acamshift.obj \
..\..\..\_temp\cvtest$(DR)_bcc\acanny.obj \
..\..\..\_temp\cvtest$(DR)_bcc\achesscorners.obj \
..\..\..\_temp\cvtest$(DR)_bcc\acondens.obj \
..\..\..\_temp\cvtest$(DR)_bcc\acontourcollection.obj \
..\..\..\_temp\cvtest$(DR)_bcc\acontourmoments.obj \
..\..\..\_temp\cvtest$(DR)_bcc\acontours.obj \
..\..\..\_temp\cvtest$(DR)_bcc\acontoursmatch.obj \
..\..\..\_temp\cvtest$(DR)_bcc\aconvert.obj \
..\..\..\_temp\cvtest$(DR)_bcc\aconvhull.obj \
..\..\..\_temp\cvtest$(DR)_bcc\acorner.obj \
..\..\..\_temp\cvtest$(DR)_bcc\acreatecontourtree.obj \
..\..\..\_temp\cvtest$(DR)_bcc\adistancetransform.obj \
..\..\..\_temp\cvtest$(DR)_bcc\adrawing.obj \
..\..\..\_temp\cvtest$(DR)_bcc\adrawing_regress.obj \
..\..\..\_temp\cvtest$(DR)_bcc\aeigenobjects.obj \
..\..\..\_temp\cvtest$(DR)_bcc\aemd.obj \
..\..\..\_temp\cvtest$(DR)_bcc\afitellipse.obj \
..\..\..\_temp\cvtest$(DR)_bcc\afitlines.obj \
..\..\..\_temp\cvtest$(DR)_bcc\afloodfill.obj \
..\..\..\_temp\cvtest$(DR)_bcc\afloodfill8.obj \
..\..\..\_temp\cvtest$(DR)_bcc\ahaar.obj \
..\..\..\_temp\cvtest$(DR)_bcc\ahistogram.obj \
..\..\..\_temp\cvtest$(DR)_bcc\ahistograms.obj \
..\..\..\_temp\cvtest$(DR)_bcc\ahmmobs.obj \
..\..\..\_temp\cvtest$(DR)_bcc\ahoughtransform.obj \
..\..\..\_temp\cvtest$(DR)_bcc\aimage.obj \
..\..\..\_temp\cvtest$(DR)_bcc\aimagestatistics.obj \
..\..\..\_temp\cvtest$(DR)_bcc\akalman.obj ..\..\..\_temp\cvtest$(DR)_bcc\akmeans.obj \
..\..\..\_temp\cvtest$(DR)_bcc\alogic.obj \
..\..\..\_temp\cvtest$(DR)_bcc\amaskaccum.obj \
..\..\..\_temp\cvtest$(DR)_bcc\amatchcontourtrees.obj \
..\..\..\_temp\cvtest$(DR)_bcc\amathutils.obj \
..\..\..\_temp\cvtest$(DR)_bcc\amatrix.obj \
..\..\..\_temp\cvtest$(DR)_bcc\amatrix2.obj \
..\..\..\_temp\cvtest$(DR)_bcc\ameanshift.obj \
..\..\..\_temp\cvtest$(DR)_bcc\aminarearect.obj \
..\..\..\_temp\cvtest$(DR)_bcc\amineval.obj \
..\..\..\_temp\cvtest$(DR)_bcc\amoments.obj \
..\..\..\_temp\cvtest$(DR)_bcc\amorphology.obj \
..\..\..\_temp\cvtest$(DR)_bcc\amotiontemplates.obj \
..\..\..\_temp\cvtest$(DR)_bcc\amotseg.obj \
..\..\..\_temp\cvtest$(DR)_bcc\anodeiterator.obj \
..\..\..\_temp\cvtest$(DR)_bcc\anorm.obj ..\..\..\_temp\cvtest$(DR)_bcc\anormmask.obj \
..\..\..\_temp\cvtest$(DR)_bcc\aoperations.obj \
..\..\..\_temp\cvtest$(DR)_bcc\aoptflowhs.obj \
..\..\..\_temp\cvtest$(DR)_bcc\aoptflowlk.obj \
..\..\..\_temp\cvtest$(DR)_bcc\aoptflowpyrlk.obj \
..\..\..\_temp\cvtest$(DR)_bcc\apixelaccess.obj \
..\..\..\_temp\cvtest$(DR)_bcc\aposit.obj \
..\..\..\_temp\cvtest$(DR)_bcc\aprecorner.obj \
..\..\..\_temp\cvtest$(DR)_bcc\apyramids.obj \
..\..\..\_temp\cvtest$(DR)_bcc\apyrsegmentation.obj \
..\..\..\_temp\cvtest$(DR)_bcc\asamplers.obj \
..\..\..\_temp\cvtest$(DR)_bcc\asequence.obj \
..\..\..\_temp\cvtest$(DR)_bcc\asnakes.obj ..\..\..\_temp\cvtest$(DR)_bcc\asobel.obj \
..\..\..\_temp\cvtest$(DR)_bcc\astoragearray.obj \
..\..\..\_temp\cvtest$(DR)_bcc\asubdivisions.obj \
..\..\..\_temp\cvtest$(DR)_bcc\asvd.obj \
..\..\..\_temp\cvtest$(DR)_bcc\atemplmatch.obj \
..\..\..\_temp\cvtest$(DR)_bcc\athresh.obj ..\..\..\_temp\cvtest$(DR)_bcc\atree.obj \
..\..\..\_temp\cvtest$(DR)_bcc\atreeiterator.obj \
..\..\..\_temp\cvtest$(DR)_bcc\ats.obj ..\..\..\_temp\cvtest$(DR)_bcc\aundistort.obj \
..\..\..\_temp\cvtest$(DR)_bcc\canny.obj ..\..\..\_temp\cvtest$(DR)_bcc\cvtest.obj \
..\..\..\_temp\cvtest$(DR)_bcc\tsysa.obj ..\..\..\_temp\cvtest$(DR)_bcc\ucontours.obj \
..\..\..\_temp\cvtest$(DR)_bcc\ugraphics.obj \
..\..\..\_temp\cvtest$(DR)_bcc\uiplutils.obj \
..\..\..\_temp\cvtest$(DR)_bcc\ureadfile.obj 



INC = ./cvtest.h 


CXXFLAGS2 = -I"../../../cvaux/include" -I"../../trs/include" -I"../../../cv/include" -I"../../../otherlibs/highgui" -I"." -3 -a8 -b- -c -d -RT- -tWM -w-inl -w-aus -j200 -o 
LINKFLAGS2 = -L"../../../lib"  -tWC -e$(OUTBIN) 

!ifdef debug

CXXFLAGS = -D"WIN32" -D"_MBCS" -D"_CONSOLE" -D"_DEBUG" -Od -v $(CXXFLAGS2)
LIBS = cvd.lib cvauxd.lib highguid.lib trsd.lib kernel32.lib user32.lib gdi32.lib comdlg32.lib advapi32.lib shell32.lib 
LINKFLAGS = $(LINKFLAGS2) 

!else

CXXFLAGS = -D"WIN32" -D"NDEBUG" -D"_CONSOLE" -D"_MBCS" -O2 $(CXXFLAGS2)
LIBS = cv.lib cvaux.lib highgui.lib trs.lib kernel32.lib user32.lib gdi32.lib comdlg32.lib advapi32.lib shell32.lib 
LINKFLAGS = $(LINKFLAGS2) 

!endif


$(OUTBIN): $(OBJS)
	-mkdir ..\..\..\bin 2> nul
	-mkdir ..\..\..\lib 2> nul
	$(LINK) @&&|
$(LINKFLAGS) $** $(LIBS) 
|
	implib $(OUTLIB) $(OUTBIN)

all: $(OUTBIN)

..\..\..\_temp\cvtest$(DR)_bcc\aabsdiff.obj: .\aabsdiff.cpp ./cvtest.h
	@-mkdir ..\..\..\_temp\cvtest$(DR)_bcc 2>nul
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_bcc\aabsdiff.obj .\aabsdiff.cpp
..\..\..\_temp\cvtest$(DR)_bcc\aaccum.obj: .\aaccum.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_bcc\aaccum.obj .\aaccum.cpp
..\..\..\_temp\cvtest$(DR)_bcc\aadaptthresh.obj: .\aadaptthresh.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_bcc\aadaptthresh.obj .\aadaptthresh.cpp
..\..\..\_temp\cvtest$(DR)_bcc\aapproxpoly.obj: .\aapproxpoly.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_bcc\aapproxpoly.obj .\aapproxpoly.cpp
..\..\..\_temp\cvtest$(DR)_bcc\aarithm.obj: .\aarithm.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_bcc\aarithm.obj .\aarithm.cpp
..\..\..\_temp\cvtest$(DR)_bcc\aarrayiterator.obj: .\aarrayiterator.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_bcc\aarrayiterator.obj .\aarrayiterator.cpp
..\..\..\_temp\cvtest$(DR)_bcc\abackproject.obj: .\abackproject.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_bcc\abackproject.obj .\abackproject.cpp
..\..\..\_temp\cvtest$(DR)_bcc\acalccontrasthist.obj: .\acalccontrasthist.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_bcc\acalccontrasthist.obj .\acalccontrasthist.cpp
..\..\..\_temp\cvtest$(DR)_bcc\acalculate.obj: .\acalculate.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_bcc\acalculate.obj .\acalculate.cpp
..\..\..\_temp\cvtest$(DR)_bcc\acameracalibration.obj: .\acameracalibration.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_bcc\acameracalibration.obj .\acameracalibration.cpp
..\..\..\_temp\cvtest$(DR)_bcc\acamshift.obj: .\acamshift.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_bcc\acamshift.obj .\acamshift.cpp
..\..\..\_temp\cvtest$(DR)_bcc\acanny.obj: .\acanny.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_bcc\acanny.obj .\acanny.cpp
..\..\..\_temp\cvtest$(DR)_bcc\achesscorners.obj: .\achesscorners.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_bcc\achesscorners.obj .\achesscorners.cpp
..\..\..\_temp\cvtest$(DR)_bcc\acondens.obj: .\acondens.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_bcc\acondens.obj .\acondens.cpp
..\..\..\_temp\cvtest$(DR)_bcc\acontourcollection.obj: .\acontourcollection.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_bcc\acontourcollection.obj .\acontourcollection.cpp
..\..\..\_temp\cvtest$(DR)_bcc\acontourmoments.obj: .\acontourmoments.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_bcc\acontourmoments.obj .\acontourmoments.cpp
..\..\..\_temp\cvtest$(DR)_bcc\acontours.obj: .\acontours.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_bcc\acontours.obj .\acontours.cpp
..\..\..\_temp\cvtest$(DR)_bcc\acontoursmatch.obj: .\acontoursmatch.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_bcc\acontoursmatch.obj .\acontoursmatch.cpp
..\..\..\_temp\cvtest$(DR)_bcc\aconvert.obj: .\aconvert.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_bcc\aconvert.obj .\aconvert.cpp
..\..\..\_temp\cvtest$(DR)_bcc\aconvhull.obj: .\aconvhull.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_bcc\aconvhull.obj .\aconvhull.cpp
..\..\..\_temp\cvtest$(DR)_bcc\acorner.obj: .\acorner.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_bcc\acorner.obj .\acorner.cpp
..\..\..\_temp\cvtest$(DR)_bcc\acreatecontourtree.obj: .\acreatecontourtree.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_bcc\acreatecontourtree.obj .\acreatecontourtree.cpp
..\..\..\_temp\cvtest$(DR)_bcc\adistancetransform.obj: .\adistancetransform.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_bcc\adistancetransform.obj .\adistancetransform.cpp
..\..\..\_temp\cvtest$(DR)_bcc\adrawing.obj: .\adrawing.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_bcc\adrawing.obj .\adrawing.cpp
..\..\..\_temp\cvtest$(DR)_bcc\adrawing_regress.obj: .\adrawing_regress.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_bcc\adrawing_regress.obj .\adrawing_regress.cpp
..\..\..\_temp\cvtest$(DR)_bcc\aeigenobjects.obj: .\aeigenobjects.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_bcc\aeigenobjects.obj .\aeigenobjects.cpp
..\..\..\_temp\cvtest$(DR)_bcc\aemd.obj: .\aemd.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_bcc\aemd.obj .\aemd.cpp
..\..\..\_temp\cvtest$(DR)_bcc\afitellipse.obj: .\afitellipse.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_bcc\afitellipse.obj .\afitellipse.cpp
..\..\..\_temp\cvtest$(DR)_bcc\afitlines.obj: .\afitlines.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_bcc\afitlines.obj .\afitlines.cpp
..\..\..\_temp\cvtest$(DR)_bcc\afloodfill.obj: .\afloodfill.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_bcc\afloodfill.obj .\afloodfill.cpp
..\..\..\_temp\cvtest$(DR)_bcc\afloodfill8.obj: .\afloodfill8.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_bcc\afloodfill8.obj .\afloodfill8.cpp
..\..\..\_temp\cvtest$(DR)_bcc\ahaar.obj: .\ahaar.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_bcc\ahaar.obj .\ahaar.cpp
..\..\..\_temp\cvtest$(DR)_bcc\ahistogram.obj: .\ahistogram.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_bcc\ahistogram.obj .\ahistogram.cpp
..\..\..\_temp\cvtest$(DR)_bcc\ahistograms.obj: .\ahistograms.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_bcc\ahistograms.obj .\ahistograms.cpp
..\..\..\_temp\cvtest$(DR)_bcc\ahmmobs.obj: .\ahmmobs.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_bcc\ahmmobs.obj .\ahmmobs.cpp
..\..\..\_temp\cvtest$(DR)_bcc\ahoughtransform.obj: .\ahoughtransform.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_bcc\ahoughtransform.obj .\ahoughtransform.cpp
..\..\..\_temp\cvtest$(DR)_bcc\aimage.obj: .\aimage.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_bcc\aimage.obj .\aimage.cpp
..\..\..\_temp\cvtest$(DR)_bcc\aimagestatistics.obj: .\aimagestatistics.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_bcc\aimagestatistics.obj .\aimagestatistics.cpp
..\..\..\_temp\cvtest$(DR)_bcc\akalman.obj: .\akalman.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_bcc\akalman.obj .\akalman.cpp
..\..\..\_temp\cvtest$(DR)_bcc\akmeans.obj: .\akmeans.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_bcc\akmeans.obj .\akmeans.cpp
..\..\..\_temp\cvtest$(DR)_bcc\alogic.obj: .\alogic.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_bcc\alogic.obj .\alogic.cpp
..\..\..\_temp\cvtest$(DR)_bcc\amaskaccum.obj: .\amaskaccum.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_bcc\amaskaccum.obj .\amaskaccum.cpp
..\..\..\_temp\cvtest$(DR)_bcc\amatchcontourtrees.obj: .\amatchcontourtrees.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_bcc\amatchcontourtrees.obj .\amatchcontourtrees.cpp
..\..\..\_temp\cvtest$(DR)_bcc\amathutils.obj: .\amathutils.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_bcc\amathutils.obj .\amathutils.cpp
..\..\..\_temp\cvtest$(DR)_bcc\amatrix.obj: .\amatrix.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_bcc\amatrix.obj .\amatrix.cpp
..\..\..\_temp\cvtest$(DR)_bcc\amatrix2.obj: .\amatrix2.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_bcc\amatrix2.obj .\amatrix2.cpp
..\..\..\_temp\cvtest$(DR)_bcc\ameanshift.obj: .\ameanshift.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_bcc\ameanshift.obj .\ameanshift.cpp
..\..\..\_temp\cvtest$(DR)_bcc\aminarearect.obj: .\aminarearect.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_bcc\aminarearect.obj .\aminarearect.cpp
..\..\..\_temp\cvtest$(DR)_bcc\amineval.obj: .\amineval.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_bcc\amineval.obj .\amineval.cpp
..\..\..\_temp\cvtest$(DR)_bcc\amoments.obj: .\amoments.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_bcc\amoments.obj .\amoments.cpp
..\..\..\_temp\cvtest$(DR)_bcc\amorphology.obj: .\amorphology.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_bcc\amorphology.obj .\amorphology.cpp
..\..\..\_temp\cvtest$(DR)_bcc\amotiontemplates.obj: .\amotiontemplates.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_bcc\amotiontemplates.obj .\amotiontemplates.cpp
..\..\..\_temp\cvtest$(DR)_bcc\amotseg.obj: .\amotseg.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_bcc\amotseg.obj .\amotseg.cpp
..\..\..\_temp\cvtest$(DR)_bcc\anodeiterator.obj: .\anodeiterator.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_bcc\anodeiterator.obj .\anodeiterator.cpp
..\..\..\_temp\cvtest$(DR)_bcc\anorm.obj: .\anorm.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_bcc\anorm.obj .\anorm.cpp
..\..\..\_temp\cvtest$(DR)_bcc\anormmask.obj: .\anormmask.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_bcc\anormmask.obj .\anormmask.cpp
..\..\..\_temp\cvtest$(DR)_bcc\aoperations.obj: .\aoperations.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_bcc\aoperations.obj .\aoperations.cpp
..\..\..\_temp\cvtest$(DR)_bcc\aoptflowhs.obj: .\aoptflowhs.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_bcc\aoptflowhs.obj .\aoptflowhs.cpp
..\..\..\_temp\cvtest$(DR)_bcc\aoptflowlk.obj: .\aoptflowlk.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_bcc\aoptflowlk.obj .\aoptflowlk.cpp
..\..\..\_temp\cvtest$(DR)_bcc\aoptflowpyrlk.obj: .\aoptflowpyrlk.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_bcc\aoptflowpyrlk.obj .\aoptflowpyrlk.cpp
..\..\..\_temp\cvtest$(DR)_bcc\apixelaccess.obj: .\apixelaccess.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_bcc\apixelaccess.obj .\apixelaccess.cpp
..\..\..\_temp\cvtest$(DR)_bcc\aposit.obj: .\aposit.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_bcc\aposit.obj .\aposit.cpp
..\..\..\_temp\cvtest$(DR)_bcc\aprecorner.obj: .\aprecorner.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_bcc\aprecorner.obj .\aprecorner.cpp
..\..\..\_temp\cvtest$(DR)_bcc\apyramids.obj: .\apyramids.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_bcc\apyramids.obj .\apyramids.cpp
..\..\..\_temp\cvtest$(DR)_bcc\apyrsegmentation.obj: .\apyrsegmentation.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_bcc\apyrsegmentation.obj .\apyrsegmentation.cpp
..\..\..\_temp\cvtest$(DR)_bcc\asamplers.obj: .\asamplers.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_bcc\asamplers.obj .\asamplers.cpp
..\..\..\_temp\cvtest$(DR)_bcc\asequence.obj: .\asequence.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_bcc\asequence.obj .\asequence.cpp
..\..\..\_temp\cvtest$(DR)_bcc\asnakes.obj: .\asnakes.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_bcc\asnakes.obj .\asnakes.cpp
..\..\..\_temp\cvtest$(DR)_bcc\asobel.obj: .\asobel.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_bcc\asobel.obj .\asobel.cpp
..\..\..\_temp\cvtest$(DR)_bcc\astoragearray.obj: .\astoragearray.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_bcc\astoragearray.obj .\astoragearray.cpp
..\..\..\_temp\cvtest$(DR)_bcc\asubdivisions.obj: .\asubdivisions.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_bcc\asubdivisions.obj .\asubdivisions.cpp
..\..\..\_temp\cvtest$(DR)_bcc\asvd.obj: .\asvd.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_bcc\asvd.obj .\asvd.cpp
..\..\..\_temp\cvtest$(DR)_bcc\atemplmatch.obj: .\atemplmatch.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_bcc\atemplmatch.obj .\atemplmatch.cpp
..\..\..\_temp\cvtest$(DR)_bcc\athresh.obj: .\athresh.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_bcc\athresh.obj .\athresh.cpp
..\..\..\_temp\cvtest$(DR)_bcc\atree.obj: .\atree.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_bcc\atree.obj .\atree.cpp
..\..\..\_temp\cvtest$(DR)_bcc\atreeiterator.obj: .\atreeiterator.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_bcc\atreeiterator.obj .\atreeiterator.cpp
..\..\..\_temp\cvtest$(DR)_bcc\ats.obj: .\ats.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_bcc\ats.obj .\ats.cpp
..\..\..\_temp\cvtest$(DR)_bcc\aundistort.obj: .\aundistort.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_bcc\aundistort.obj .\aundistort.cpp
..\..\..\_temp\cvtest$(DR)_bcc\canny.obj: .\canny.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_bcc\canny.obj .\canny.cpp
..\..\..\_temp\cvtest$(DR)_bcc\cvtest.obj: .\cvtest.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_bcc\cvtest.obj .\cvtest.cpp
..\..\..\_temp\cvtest$(DR)_bcc\tsysa.obj: .\tsysa.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_bcc\tsysa.obj .\tsysa.cpp
..\..\..\_temp\cvtest$(DR)_bcc\ucontours.obj: .\ucontours.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_bcc\ucontours.obj .\ucontours.cpp
..\..\..\_temp\cvtest$(DR)_bcc\ugraphics.obj: .\ugraphics.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_bcc\ugraphics.obj .\ugraphics.cpp
..\..\..\_temp\cvtest$(DR)_bcc\uiplutils.obj: .\uiplutils.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_bcc\uiplutils.obj .\uiplutils.cpp
..\..\..\_temp\cvtest$(DR)_bcc\ureadfile.obj: .\ureadfile.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_bcc\ureadfile.obj .\ureadfile.cpp
