# Makefile for GNU C/C++ >=2.95.3

CXX = g++
LINK = g++

ifdef debug

SUFFIX = d
DR = _Dbg

else

SUFFIX = 
DR = _Rls

endif

OUTBIN = ..\..\..\bin\cvtest$(SUFFIX).exe
OUTLIB = ..\..\..\lib\libcvtest$(SUFFIX).a

OBJS = ..\..\..\_temp\cvtest$(DR)_gcc\aabsdiff.o \
..\..\..\_temp\cvtest$(DR)_gcc\aaccum.o ..\..\..\_temp\cvtest$(DR)_gcc\aadaptthresh.o \
..\..\..\_temp\cvtest$(DR)_gcc\aapproxpoly.o ..\..\..\_temp\cvtest$(DR)_gcc\aarithm.o \
..\..\..\_temp\cvtest$(DR)_gcc\aarrayiterator.o \
..\..\..\_temp\cvtest$(DR)_gcc\abackproject.o \
..\..\..\_temp\cvtest$(DR)_gcc\acalccontrasthist.o \
..\..\..\_temp\cvtest$(DR)_gcc\acalculate.o \
..\..\..\_temp\cvtest$(DR)_gcc\acameracalibration.o \
..\..\..\_temp\cvtest$(DR)_gcc\acamshift.o ..\..\..\_temp\cvtest$(DR)_gcc\acanny.o \
..\..\..\_temp\cvtest$(DR)_gcc\achesscorners.o \
..\..\..\_temp\cvtest$(DR)_gcc\acondens.o \
..\..\..\_temp\cvtest$(DR)_gcc\acontourcollection.o \
..\..\..\_temp\cvtest$(DR)_gcc\acontourmoments.o \
..\..\..\_temp\cvtest$(DR)_gcc\acontours.o \
..\..\..\_temp\cvtest$(DR)_gcc\acontoursmatch.o \
..\..\..\_temp\cvtest$(DR)_gcc\aconvert.o ..\..\..\_temp\cvtest$(DR)_gcc\aconvhull.o \
..\..\..\_temp\cvtest$(DR)_gcc\acorner.o \
..\..\..\_temp\cvtest$(DR)_gcc\acreatecontourtree.o \
..\..\..\_temp\cvtest$(DR)_gcc\adistancetransform.o \
..\..\..\_temp\cvtest$(DR)_gcc\adrawing.o \
..\..\..\_temp\cvtest$(DR)_gcc\adrawing_regress.o \
..\..\..\_temp\cvtest$(DR)_gcc\aeigenobjects.o ..\..\..\_temp\cvtest$(DR)_gcc\aemd.o \
..\..\..\_temp\cvtest$(DR)_gcc\afitellipse.o \
..\..\..\_temp\cvtest$(DR)_gcc\afitlines.o \
..\..\..\_temp\cvtest$(DR)_gcc\afloodfill.o \
..\..\..\_temp\cvtest$(DR)_gcc\afloodfill8.o ..\..\..\_temp\cvtest$(DR)_gcc\ahaar.o \
..\..\..\_temp\cvtest$(DR)_gcc\ahistogram.o \
..\..\..\_temp\cvtest$(DR)_gcc\ahistograms.o ..\..\..\_temp\cvtest$(DR)_gcc\ahmmobs.o \
..\..\..\_temp\cvtest$(DR)_gcc\ahoughtransform.o \
..\..\..\_temp\cvtest$(DR)_gcc\aimage.o \
..\..\..\_temp\cvtest$(DR)_gcc\aimagestatistics.o \
..\..\..\_temp\cvtest$(DR)_gcc\akalman.o ..\..\..\_temp\cvtest$(DR)_gcc\akmeans.o \
..\..\..\_temp\cvtest$(DR)_gcc\alogic.o ..\..\..\_temp\cvtest$(DR)_gcc\amaskaccum.o \
..\..\..\_temp\cvtest$(DR)_gcc\amatchcontourtrees.o \
..\..\..\_temp\cvtest$(DR)_gcc\amathutils.o ..\..\..\_temp\cvtest$(DR)_gcc\amatrix.o \
..\..\..\_temp\cvtest$(DR)_gcc\amatrix2.o ..\..\..\_temp\cvtest$(DR)_gcc\ameanshift.o \
..\..\..\_temp\cvtest$(DR)_gcc\aminarearect.o \
..\..\..\_temp\cvtest$(DR)_gcc\amineval.o ..\..\..\_temp\cvtest$(DR)_gcc\amoments.o \
..\..\..\_temp\cvtest$(DR)_gcc\amorphology.o \
..\..\..\_temp\cvtest$(DR)_gcc\amotiontemplates.o \
..\..\..\_temp\cvtest$(DR)_gcc\amotseg.o \
..\..\..\_temp\cvtest$(DR)_gcc\anodeiterator.o ..\..\..\_temp\cvtest$(DR)_gcc\anorm.o \
..\..\..\_temp\cvtest$(DR)_gcc\anormmask.o \
..\..\..\_temp\cvtest$(DR)_gcc\aoperations.o \
..\..\..\_temp\cvtest$(DR)_gcc\aoptflowhs.o \
..\..\..\_temp\cvtest$(DR)_gcc\aoptflowlk.o \
..\..\..\_temp\cvtest$(DR)_gcc\aoptflowpyrlk.o \
..\..\..\_temp\cvtest$(DR)_gcc\apixelaccess.o ..\..\..\_temp\cvtest$(DR)_gcc\aposit.o \
..\..\..\_temp\cvtest$(DR)_gcc\aprecorner.o \
..\..\..\_temp\cvtest$(DR)_gcc\apyramids.o \
..\..\..\_temp\cvtest$(DR)_gcc\apyrsegmentation.o \
..\..\..\_temp\cvtest$(DR)_gcc\asamplers.o ..\..\..\_temp\cvtest$(DR)_gcc\asequence.o \
..\..\..\_temp\cvtest$(DR)_gcc\asnakes.o ..\..\..\_temp\cvtest$(DR)_gcc\asobel.o \
..\..\..\_temp\cvtest$(DR)_gcc\astoragearray.o \
..\..\..\_temp\cvtest$(DR)_gcc\asubdivisions.o ..\..\..\_temp\cvtest$(DR)_gcc\asvd.o \
..\..\..\_temp\cvtest$(DR)_gcc\atemplmatch.o ..\..\..\_temp\cvtest$(DR)_gcc\athresh.o \
..\..\..\_temp\cvtest$(DR)_gcc\atree.o ..\..\..\_temp\cvtest$(DR)_gcc\atreeiterator.o \
..\..\..\_temp\cvtest$(DR)_gcc\ats.o ..\..\..\_temp\cvtest$(DR)_gcc\aundistort.o \
..\..\..\_temp\cvtest$(DR)_gcc\canny.o ..\..\..\_temp\cvtest$(DR)_gcc\cvtest.o \
..\..\..\_temp\cvtest$(DR)_gcc\tsysa.o ..\..\..\_temp\cvtest$(DR)_gcc\ucontours.o \
..\..\..\_temp\cvtest$(DR)_gcc\ugraphics.o ..\..\..\_temp\cvtest$(DR)_gcc\uiplutils.o \
..\..\..\_temp\cvtest$(DR)_gcc\ureadfile.o 

OBJ_SHRT = aabsdiff.o aaccum.o aadaptthresh.o aapproxpoly.o aarithm.o \
aarrayiterator.o abackproject.o acalccontrasthist.o acalculate.o acameracalibration.o \
acamshift.o acanny.o achesscorners.o acondens.o acontourcollection.o \
acontourmoments.o acontours.o acontoursmatch.o aconvert.o aconvhull.o acorner.o \
acreatecontourtree.o adistancetransform.o adrawing.o adrawing_regress.o \
aeigenobjects.o aemd.o afitellipse.o afitlines.o afloodfill.o afloodfill8.o ahaar.o \
ahistogram.o ahistograms.o ahmmobs.o ahoughtransform.o aimage.o aimagestatistics.o \
akalman.o akmeans.o alogic.o amaskaccum.o amatchcontourtrees.o amathutils.o amatrix.o \
amatrix2.o ameanshift.o aminarearect.o amineval.o amoments.o amorphology.o \
amotiontemplates.o amotseg.o anodeiterator.o anorm.o anormmask.o aoperations.o \
aoptflowhs.o aoptflowlk.o aoptflowpyrlk.o apixelaccess.o aposit.o aprecorner.o \
apyramids.o apyrsegmentation.o asamplers.o asequence.o asnakes.o asobel.o \
astoragearray.o asubdivisions.o asvd.o atemplmatch.o athresh.o atree.o \
atreeiterator.o ats.o aundistort.o canny.o cvtest.o tsysa.o ucontours.o ugraphics.o \
uiplutils.o ureadfile.o 



INC = ./cvtest.h 


CXXFLAGS2 = -I"../../../cvaux/include" -I"../../trs/include" -I"../../../cv/include" -I"../../../otherlibs/highgui" -I"." -Wall -c -fvtable-thunks=2 -o 
LINKFLAGS2 = -L"../../../lib" -o$(OUTBIN) -Wl,-call_shared 

ifdef debug

CXXFLAGS = -D"WIN32" -D"_MBCS" -D"_CONSOLE" -D"_DEBUG" -O0 -ggdb3 $(CXXFLAGS2)
LIBS = -lcvd -lcvauxd -lhighguid -ltrsd -lkernel32 -luser32 -lgdi32 -lcomdlg32 -ladvapi32 -lshell32 
LINKFLAGS = $(LINKFLAGS2) 

else

CXXFLAGS = -D"WIN32" -D"NDEBUG" -D"_CONSOLE" -D"_MBCS" -O3 -g -fomit-frame-pointer -mcpu=i686 -march=i386 -ffast-math $(CXXFLAGS2)
LIBS = -lcv -lcvaux -lhighgui -ltrs -lkernel32 -luser32 -lgdi32 -lcomdlg32 -ladvapi32 -lshell32 
LINKFLAGS = $(LINKFLAGS2) 

endif


$(OUTBIN): $(OBJS)
	-mkdir ..\..\..\bin 2> nul
	-mkdir ..\..\..\lib 2> nul
	-move "..\..\..\_temp\cvtest$(DR)_gcc\*.o" .
	$(LINK) $(LINKFLAGS) $(OBJ_SHRT) $(LIBS)
	-move *.o "..\..\..\_temp\cvtest$(DR)_gcc"

all: $(OUTBIN)

..\..\..\_temp\cvtest$(DR)_gcc\aabsdiff.o: .\aabsdiff.cpp ./cvtest.h
	@-mkdir ..\..\..\_temp\cvtest$(DR)_gcc 2>nul
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_gcc\aabsdiff.o .\aabsdiff.cpp
..\..\..\_temp\cvtest$(DR)_gcc\aaccum.o: .\aaccum.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_gcc\aaccum.o .\aaccum.cpp
..\..\..\_temp\cvtest$(DR)_gcc\aadaptthresh.o: .\aadaptthresh.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_gcc\aadaptthresh.o .\aadaptthresh.cpp
..\..\..\_temp\cvtest$(DR)_gcc\aapproxpoly.o: .\aapproxpoly.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_gcc\aapproxpoly.o .\aapproxpoly.cpp
..\..\..\_temp\cvtest$(DR)_gcc\aarithm.o: .\aarithm.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_gcc\aarithm.o .\aarithm.cpp
..\..\..\_temp\cvtest$(DR)_gcc\aarrayiterator.o: .\aarrayiterator.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_gcc\aarrayiterator.o .\aarrayiterator.cpp
..\..\..\_temp\cvtest$(DR)_gcc\abackproject.o: .\abackproject.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_gcc\abackproject.o .\abackproject.cpp
..\..\..\_temp\cvtest$(DR)_gcc\acalccontrasthist.o: .\acalccontrasthist.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_gcc\acalccontrasthist.o .\acalccontrasthist.cpp
..\..\..\_temp\cvtest$(DR)_gcc\acalculate.o: .\acalculate.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_gcc\acalculate.o .\acalculate.cpp
..\..\..\_temp\cvtest$(DR)_gcc\acameracalibration.o: .\acameracalibration.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_gcc\acameracalibration.o .\acameracalibration.cpp
..\..\..\_temp\cvtest$(DR)_gcc\acamshift.o: .\acamshift.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_gcc\acamshift.o .\acamshift.cpp
..\..\..\_temp\cvtest$(DR)_gcc\acanny.o: .\acanny.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_gcc\acanny.o .\acanny.cpp
..\..\..\_temp\cvtest$(DR)_gcc\achesscorners.o: .\achesscorners.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_gcc\achesscorners.o .\achesscorners.cpp
..\..\..\_temp\cvtest$(DR)_gcc\acondens.o: .\acondens.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_gcc\acondens.o .\acondens.cpp
..\..\..\_temp\cvtest$(DR)_gcc\acontourcollection.o: .\acontourcollection.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_gcc\acontourcollection.o .\acontourcollection.cpp
..\..\..\_temp\cvtest$(DR)_gcc\acontourmoments.o: .\acontourmoments.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_gcc\acontourmoments.o .\acontourmoments.cpp
..\..\..\_temp\cvtest$(DR)_gcc\acontours.o: .\acontours.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_gcc\acontours.o .\acontours.cpp
..\..\..\_temp\cvtest$(DR)_gcc\acontoursmatch.o: .\acontoursmatch.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_gcc\acontoursmatch.o .\acontoursmatch.cpp
..\..\..\_temp\cvtest$(DR)_gcc\aconvert.o: .\aconvert.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_gcc\aconvert.o .\aconvert.cpp
..\..\..\_temp\cvtest$(DR)_gcc\aconvhull.o: .\aconvhull.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_gcc\aconvhull.o .\aconvhull.cpp
..\..\..\_temp\cvtest$(DR)_gcc\acorner.o: .\acorner.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_gcc\acorner.o .\acorner.cpp
..\..\..\_temp\cvtest$(DR)_gcc\acreatecontourtree.o: .\acreatecontourtree.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_gcc\acreatecontourtree.o .\acreatecontourtree.cpp
..\..\..\_temp\cvtest$(DR)_gcc\adistancetransform.o: .\adistancetransform.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_gcc\adistancetransform.o .\adistancetransform.cpp
..\..\..\_temp\cvtest$(DR)_gcc\adrawing.o: .\adrawing.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_gcc\adrawing.o .\adrawing.cpp
..\..\..\_temp\cvtest$(DR)_gcc\adrawing_regress.o: .\adrawing_regress.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_gcc\adrawing_regress.o .\adrawing_regress.cpp
..\..\..\_temp\cvtest$(DR)_gcc\aeigenobjects.o: .\aeigenobjects.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_gcc\aeigenobjects.o .\aeigenobjects.cpp
..\..\..\_temp\cvtest$(DR)_gcc\aemd.o: .\aemd.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_gcc\aemd.o .\aemd.cpp
..\..\..\_temp\cvtest$(DR)_gcc\afitellipse.o: .\afitellipse.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_gcc\afitellipse.o .\afitellipse.cpp
..\..\..\_temp\cvtest$(DR)_gcc\afitlines.o: .\afitlines.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_gcc\afitlines.o .\afitlines.cpp
..\..\..\_temp\cvtest$(DR)_gcc\afloodfill.o: .\afloodfill.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_gcc\afloodfill.o .\afloodfill.cpp
..\..\..\_temp\cvtest$(DR)_gcc\afloodfill8.o: .\afloodfill8.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_gcc\afloodfill8.o .\afloodfill8.cpp
..\..\..\_temp\cvtest$(DR)_gcc\ahaar.o: .\ahaar.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_gcc\ahaar.o .\ahaar.cpp
..\..\..\_temp\cvtest$(DR)_gcc\ahistogram.o: .\ahistogram.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_gcc\ahistogram.o .\ahistogram.cpp
..\..\..\_temp\cvtest$(DR)_gcc\ahistograms.o: .\ahistograms.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_gcc\ahistograms.o .\ahistograms.cpp
..\..\..\_temp\cvtest$(DR)_gcc\ahmmobs.o: .\ahmmobs.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_gcc\ahmmobs.o .\ahmmobs.cpp
..\..\..\_temp\cvtest$(DR)_gcc\ahoughtransform.o: .\ahoughtransform.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_gcc\ahoughtransform.o .\ahoughtransform.cpp
..\..\..\_temp\cvtest$(DR)_gcc\aimage.o: .\aimage.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_gcc\aimage.o .\aimage.cpp
..\..\..\_temp\cvtest$(DR)_gcc\aimagestatistics.o: .\aimagestatistics.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_gcc\aimagestatistics.o .\aimagestatistics.cpp
..\..\..\_temp\cvtest$(DR)_gcc\akalman.o: .\akalman.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_gcc\akalman.o .\akalman.cpp
..\..\..\_temp\cvtest$(DR)_gcc\akmeans.o: .\akmeans.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_gcc\akmeans.o .\akmeans.cpp
..\..\..\_temp\cvtest$(DR)_gcc\alogic.o: .\alogic.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_gcc\alogic.o .\alogic.cpp
..\..\..\_temp\cvtest$(DR)_gcc\amaskaccum.o: .\amaskaccum.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_gcc\amaskaccum.o .\amaskaccum.cpp
..\..\..\_temp\cvtest$(DR)_gcc\amatchcontourtrees.o: .\amatchcontourtrees.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_gcc\amatchcontourtrees.o .\amatchcontourtrees.cpp
..\..\..\_temp\cvtest$(DR)_gcc\amathutils.o: .\amathutils.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_gcc\amathutils.o .\amathutils.cpp
..\..\..\_temp\cvtest$(DR)_gcc\amatrix.o: .\amatrix.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_gcc\amatrix.o .\amatrix.cpp
..\..\..\_temp\cvtest$(DR)_gcc\amatrix2.o: .\amatrix2.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_gcc\amatrix2.o .\amatrix2.cpp
..\..\..\_temp\cvtest$(DR)_gcc\ameanshift.o: .\ameanshift.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_gcc\ameanshift.o .\ameanshift.cpp
..\..\..\_temp\cvtest$(DR)_gcc\aminarearect.o: .\aminarearect.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_gcc\aminarearect.o .\aminarearect.cpp
..\..\..\_temp\cvtest$(DR)_gcc\amineval.o: .\amineval.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_gcc\amineval.o .\amineval.cpp
..\..\..\_temp\cvtest$(DR)_gcc\amoments.o: .\amoments.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_gcc\amoments.o .\amoments.cpp
..\..\..\_temp\cvtest$(DR)_gcc\amorphology.o: .\amorphology.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_gcc\amorphology.o .\amorphology.cpp
..\..\..\_temp\cvtest$(DR)_gcc\amotiontemplates.o: .\amotiontemplates.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_gcc\amotiontemplates.o .\amotiontemplates.cpp
..\..\..\_temp\cvtest$(DR)_gcc\amotseg.o: .\amotseg.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_gcc\amotseg.o .\amotseg.cpp
..\..\..\_temp\cvtest$(DR)_gcc\anodeiterator.o: .\anodeiterator.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_gcc\anodeiterator.o .\anodeiterator.cpp
..\..\..\_temp\cvtest$(DR)_gcc\anorm.o: .\anorm.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_gcc\anorm.o .\anorm.cpp
..\..\..\_temp\cvtest$(DR)_gcc\anormmask.o: .\anormmask.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_gcc\anormmask.o .\anormmask.cpp
..\..\..\_temp\cvtest$(DR)_gcc\aoperations.o: .\aoperations.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_gcc\aoperations.o .\aoperations.cpp
..\..\..\_temp\cvtest$(DR)_gcc\aoptflowhs.o: .\aoptflowhs.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_gcc\aoptflowhs.o .\aoptflowhs.cpp
..\..\..\_temp\cvtest$(DR)_gcc\aoptflowlk.o: .\aoptflowlk.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_gcc\aoptflowlk.o .\aoptflowlk.cpp
..\..\..\_temp\cvtest$(DR)_gcc\aoptflowpyrlk.o: .\aoptflowpyrlk.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_gcc\aoptflowpyrlk.o .\aoptflowpyrlk.cpp
..\..\..\_temp\cvtest$(DR)_gcc\apixelaccess.o: .\apixelaccess.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_gcc\apixelaccess.o .\apixelaccess.cpp
..\..\..\_temp\cvtest$(DR)_gcc\aposit.o: .\aposit.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_gcc\aposit.o .\aposit.cpp
..\..\..\_temp\cvtest$(DR)_gcc\aprecorner.o: .\aprecorner.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_gcc\aprecorner.o .\aprecorner.cpp
..\..\..\_temp\cvtest$(DR)_gcc\apyramids.o: .\apyramids.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_gcc\apyramids.o .\apyramids.cpp
..\..\..\_temp\cvtest$(DR)_gcc\apyrsegmentation.o: .\apyrsegmentation.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_gcc\apyrsegmentation.o .\apyrsegmentation.cpp
..\..\..\_temp\cvtest$(DR)_gcc\asamplers.o: .\asamplers.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_gcc\asamplers.o .\asamplers.cpp
..\..\..\_temp\cvtest$(DR)_gcc\asequence.o: .\asequence.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_gcc\asequence.o .\asequence.cpp
..\..\..\_temp\cvtest$(DR)_gcc\asnakes.o: .\asnakes.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_gcc\asnakes.o .\asnakes.cpp
..\..\..\_temp\cvtest$(DR)_gcc\asobel.o: .\asobel.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_gcc\asobel.o .\asobel.cpp
..\..\..\_temp\cvtest$(DR)_gcc\astoragearray.o: .\astoragearray.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_gcc\astoragearray.o .\astoragearray.cpp
..\..\..\_temp\cvtest$(DR)_gcc\asubdivisions.o: .\asubdivisions.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_gcc\asubdivisions.o .\asubdivisions.cpp
..\..\..\_temp\cvtest$(DR)_gcc\asvd.o: .\asvd.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_gcc\asvd.o .\asvd.cpp
..\..\..\_temp\cvtest$(DR)_gcc\atemplmatch.o: .\atemplmatch.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_gcc\atemplmatch.o .\atemplmatch.cpp
..\..\..\_temp\cvtest$(DR)_gcc\athresh.o: .\athresh.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_gcc\athresh.o .\athresh.cpp
..\..\..\_temp\cvtest$(DR)_gcc\atree.o: .\atree.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_gcc\atree.o .\atree.cpp
..\..\..\_temp\cvtest$(DR)_gcc\atreeiterator.o: .\atreeiterator.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_gcc\atreeiterator.o .\atreeiterator.cpp
..\..\..\_temp\cvtest$(DR)_gcc\ats.o: .\ats.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_gcc\ats.o .\ats.cpp
..\..\..\_temp\cvtest$(DR)_gcc\aundistort.o: .\aundistort.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_gcc\aundistort.o .\aundistort.cpp
..\..\..\_temp\cvtest$(DR)_gcc\canny.o: .\canny.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_gcc\canny.o .\canny.cpp
..\..\..\_temp\cvtest$(DR)_gcc\cvtest.o: .\cvtest.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_gcc\cvtest.o .\cvtest.cpp
..\..\..\_temp\cvtest$(DR)_gcc\tsysa.o: .\tsysa.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_gcc\tsysa.o .\tsysa.cpp
..\..\..\_temp\cvtest$(DR)_gcc\ucontours.o: .\ucontours.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_gcc\ucontours.o .\ucontours.cpp
..\..\..\_temp\cvtest$(DR)_gcc\ugraphics.o: .\ugraphics.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_gcc\ugraphics.o .\ugraphics.cpp
..\..\..\_temp\cvtest$(DR)_gcc\uiplutils.o: .\uiplutils.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_gcc\uiplutils.o .\uiplutils.cpp
..\..\..\_temp\cvtest$(DR)_gcc\ureadfile.o: .\ureadfile.cpp ./cvtest.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\cvtest$(DR)_gcc\ureadfile.o .\ureadfile.cpp
