#usr/share/opencv/doc/CMakeLists.txt
#usr/share/opencv/doc/ChangeLog.htm
#usr/share/opencv/doc/README.txt
#usr/share/opencv/doc/haartraining.htm
#usr/share/opencv/doc/index.htm
#usr/share/opencv/doc/opencv-logo.png
#usr/share/opencv/doc/opencv-logo2.png
#usr/share/opencv/doc/opencv.jpg
#usr/share/opencv/doc/opencv.pdf
#usr/share/opencv/doc/packaging.txt
#usr/share/opencv/doc/papers
#usr/share/opencv/doc/pattern.pdf
#usr/share/opencv/doc/vidsurv
usr/share/opencv/doc/*		usr/share/doc/opencv-doc/
usr/share/opencv/haarcascades	usr/share/doc/opencv-doc/examples/haarcascades
usr/share/opencv/lbpcascades	usr/share/doc/opencv-doc/examples/lbpcascades
usr/share/opencv/samples/c	usr/share/doc/opencv-doc/examples/c
usr/share/opencv/samples/python usr/share/doc/opencv-doc/examples/python
#../../samples/c/Makefile.debian	usr/share/doc/opencv-doc/examples/c/
