# Makefile for GNU C/C++ >=2.95.3

CXX = g++
LINK = g++

ifdef debug

SUFFIX = d
DR = _Dbg

else

SUFFIX = 
DR = _Rls

endif

OUTBIN = ..\..\..\bin\trs$(SUFFIX).dll
OUTLIB = ..\..\..\lib\libtrs$(SUFFIX).a

OBJS = ..\..\..\_temp\trs$(DR)_gcc\trsapi.o ..\..\..\_temp\trs$(DR)_gcc\trserror.o \
..\..\..\_temp\trs$(DR)_gcc\trsread.o 

OBJ_SHRT = trsapi.o trserror.o trsread.o 



INC = ../include/trsapi.h ../include/trserror.h ../include/trsipi.h \
../include/trswind.h 


CXXFLAGS2 = -I"../../../ippicvlib/include" -I"../include" -Wall -c -fvtable-thunks=2 -o 
LINKFLAGS2 = -o$(OUTBIN) -shared -Wl,-call_shared,--out-implib,$(OUTLIB) 

ifdef debug

CXXFLAGS = -D"_CVL_PX" -D"WIN32" -D"_CVL_DEBUG" -D"_DEBUG" -D"TRS_W32DLL" -D"_WINDOWS" -O0 -ggdb3 $(CXXFLAGS2)
LIBS = -lkernel32 -luser32 -lgdi32 
LINKFLAGS = $(LINKFLAGS2) 

else

CXXFLAGS = -D"_CVL_PX" -D"NDEBUG" -D"TRS_W32DLL" -D"WIN32" -D"_WINDOWS" -O3 -g -fomit-frame-pointer -mcpu=i686 -march=i386 -ffast-math $(CXXFLAGS2)
LIBS = -lkernel32 -luser32 -lgdi32 
LINKFLAGS = $(LINKFLAGS2) 

endif


$(OUTBIN): $(OBJS)
	-mkdir ..\..\..\bin 2> nul
	-mkdir ..\..\..\lib 2> nul
	-move "..\..\..\_temp\trs$(DR)_gcc\*.o" .
	$(LINK) $(LINKFLAGS) $(OBJ_SHRT) $(LIBS)
	-move *.o "..\..\..\_temp\trs$(DR)_gcc"

all: $(OUTBIN)

..\..\..\_temp\trs$(DR)_gcc\trsapi.o: ..\src\trsapi.c ../include/trsapi.h ../include/trserror.h ../include/trsipi.h ../include/trswind.h
	@-mkdir ..\..\..\_temp\trs$(DR)_gcc 2>nul
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\trs$(DR)_gcc\trsapi.o ..\src\trsapi.c
..\..\..\_temp\trs$(DR)_gcc\trserror.o: ..\src\trserror.c ../include/trsapi.h ../include/trserror.h ../include/trsipi.h ../include/trswind.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\trs$(DR)_gcc\trserror.o ..\src\trserror.c
..\..\..\_temp\trs$(DR)_gcc\trsread.o: ..\src\trsread.c ../include/trsapi.h ../include/trserror.h ../include/trsipi.h ../include/trswind.h
	-$(CXX) $(CXXFLAGS)..\..\..\_temp\trs$(DR)_gcc\trsread.o ..\src\trsread.c
